### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by jludvice** [syndesisio/token-rp#2]
What does this mean? Is it a problem? Why is it complaining?
```
2017/06/29 10:05:49 http: TLS handshake error from 172.17.0.1:59072: EOF
2017/06/29 10:05:49 http: TLS handshake error from 172.17.0.1:59070: EOF
2017/06/29 10:05:59 http: TLS handshake error from 172.17.0.1:59144: EOF
2017/06/29 10:05:59 http: TLS handshake error from 172.17.0.1:59136: EOF
```

**Comment by jimmidyson** [comment]
Updating now

**Comment by jludvice** [comment]
@jimmidyson I tried to include some flags in log configuration, just hadn't a chance to deploy the updated container and see how it works (https://github.com/jludvice/token-rp/commit/1dbf67d6713c94ccd8416aaf63e779e09013347d)

**Comment by jludvice** [comment]
I gues we can close this issue @jimmidyson ?
